soc: silabs: siwx91x: Fix corrupted firmware
Since, commit 2f7d13840f6 ("kconfig: Fix CONFIG_FLASH_LOAD_OFFSET for non-0
starting addresses"), the way to compute offsets in the flash memory has
changed.

With this change, the arguments passed to siwx91x_isp_prepare.py were not
correct anymore and "west flash" ended up with:

   ERROR: Waiting for flashloader failed: 108 - Checksum error

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>